# Default initial positions for so_100_arm's ros2_control fake system

initial_positions:
  Elbow: -1.6
  Gripper: -1.5
  Shoulder_Pitch: 1.6
  Shoulder_Rotation: 0
  Wrist_Pitch: 0.0
  Wrist_Roll: 1.2
